-- Add OVERWEIGHT risk level for KMS growth classification
ALTER TABLE `Checkup`
  MODIFY `riskLevel` ENUM('NORMAL', 'ATTENTION', 'STUNTING_RISK', 'UNDERNUTRITION', 'OVERWEIGHT') NOT NULL;

ALTER TABLE `GrowthStatusLog`
  MODIFY `riskLevel` ENUM('NORMAL', 'ATTENTION', 'STUNTING_RISK', 'UNDERNUTRITION', 'OVERWEIGHT') NOT NULL;
